"""add_user_id_indexes

Revision ID: 3acddf2954f1
Revises: c9639ae79332
Create Date: 2026-04-20 18:47:04.794999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acddf2954f1'
down_revision: Union[str, Sequence[str], None] = 'c9639ae79332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.drop_constraint(op.f('medical_histories_user_id_key'), 'medical_histories', type_='unique')
    op.create_index(op.f('ix_medical_histories_user_id'), 'medical_histories', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_histories_user_id'), table_name='medical_histories')
    op.create_unique_constraint(op.f('medical_histories_user_id_key'), 'medical_histories', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    # ### end Alembic commands ###
