"""Align frontend conditions schema

Revision ID: c9639ae79332
Revises: 3a9dd4cd3a1a
Create Date: 2026-04-20 02:07:32.630328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9639ae79332'
down_revision: Union[str, Sequence[str], None] = '3a9dd4cd3a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_histories', sa.Column('conditions', sa.JSON(), nullable=True))
    op.add_column('medical_histories', sa.Column('other', sa.Text(), nullable=True))
    op.drop_column('medical_histories', 'chronic_conditions')
    op.drop_column('medical_histories', 'allergies')
    op.drop_column('medical_histories', 'daily_medications')
    op.drop_column('users', 'blood_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blood_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medical_histories', sa.Column('daily_medications', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_histories', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medical_histories', sa.Column('chronic_conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('medical_histories', 'other')
    op.drop_column('medical_histories', 'conditions')
    # ### end Alembic commands ###
